version: '3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    command: [ "--port", "27017" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin