version: '3'
services:
  postgres:
    image: postgres:13.0
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
    entrypoint: redis-cli
  mongo:
    image: mongo:4.4
    restart: always
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27018" ]
    ports:
      - '27018:27018'
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"localhost:27018\"}]}).ok || rs.status().ok" | mongo --port 27018 --quiet) -eq 1
      interval: 10s
  ad:
    image: ad
    ports:
      - '10389:10389'